// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BusinessObject.Model
{
    public partial class Account
    {
        public Account()
        {
            BookRoom = new HashSet<BookRoom>();
        }
        [Required(ErrorMessage = "Id can not be empty")]
        public int Id { get; set; }
        [EmailAddress(ErrorMessage = "Wrong format for email address")]
        [Required(ErrorMessage = "Email can not be empty")]
        public string Email { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Email can not be empty")]
        [StringLength(maximumLength: 20,
                        ErrorMessage = "Password's lenght must be between 6-20",
                        MinimumLength = 6)]
        public string Password { get; set; }
        [Required(ErrorMessage = "Full name can not be empty")]
        [Display(Name = "Full Name")]
        [StringLength(maximumLength: 50,
                       MinimumLength = 6,
                       ErrorMessage = "Full name's length must be between 6-50 characters")]
        public string Fullname { get; set; }
        [Required(ErrorMessage = "Avatar  can not be empty")]
        public string Avartar { get; set; }
        [Required(ErrorMessage = "Phone can not be empty")]
        [RegularExpression("[0-9]{10}", ErrorMessage = "Wrong format for phone number")]
        public string Phone { get; set; }
        public bool? Gender { get; set; }
        public bool? IsEmployee { get; set; }
        public bool? Active { get; set; }

        public virtual ICollection<BookRoom> BookRoom { get; set; }
    }
}