// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BusinessObject.Model
{
    public partial class Room
    {
        public Room()
        {
            RoomInBooking = new HashSet<RoomInBooking>();
        }

        [Required(ErrorMessage = "Id can not be empty")]
        public int Id { get; set; }
        public int? RoomTypeId { get; set; }
        [Required(ErrorMessage = "Room name can not be empty")]
        [Display(Name = "Room Name")]
        [StringLength(maximumLength: 50,
                      MinimumLength = 2,
                      ErrorMessage = "Room name's length must be between 2-50 characters")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Image  can not be empty")]
        public string Image { get; set; }
        [Required(ErrorMessage = "Description name can not be empty")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Amount can not be empty")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Wrong format for Amount number")]
        public decimal? Amount { get; set; }
        public bool? Active { get; set; }
         

        public virtual RoomType RoomType { get; set; }
        public virtual ICollection<RoomInBooking> RoomInBooking { get; set; }
    }
}