// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BusinessObject.Model
{
    public partial class RoomType
    {
        public RoomType()
        {
            Room = new HashSet<Room>();
        }
        [Required(ErrorMessage = "Id can not be empty")]
        public int Id { get; set; }
        [Required(ErrorMessage = "Room Type can not be empty")]
        [Display(Name = "Room Type")]
        [StringLength(maximumLength: 50,
                     MinimumLength = 2,
                     ErrorMessage = "Room Type's length must be between 2-50 characters")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Description Type can not be empty")]
        public string Description { get; set; }
        public bool? Active { get; set; }

        public virtual ICollection<Room> Room { get; set; }
    }
}