// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Model
{
    public partial class RoomInBooking
    {
        public int BookRoomId { get; set; }
        public int RoomId { get; set; }

        public virtual BookRoom BookRoom { get; set; }
        public virtual Room Room { get; set; }
    }
}