// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Model
{
    public partial class ServiceInRoom
    {
        public int BookRoomId { get; set; }
        public int ServiceId { get; set; }

        public int? Quantity { get; set; }
        public virtual BookRoom BookRoom { get; set; }
        public virtual Service Service { get; set; }
    }
}