// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BusinessObject.Model
{
    public partial class Service
    {
        public Service()
        {
            ServiceInRoom = new HashSet<ServiceInRoom>();
        }
        [Required(ErrorMessage = "Id can not be empty")]
        public int Id { get; set; }
        public int? ServiceTypeId { get; set; }
        [Required(ErrorMessage = "Service Name can not be empty")]
        [Display(Name = "Service Name")]
        [StringLength(maximumLength: 50,
                    MinimumLength = 2,
                    ErrorMessage = "Service Name's length must be between 2-50 characters")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Image  can not be empty")]
        public string Image { get; set; }
        [Required(ErrorMessage = "InStock can not be empty")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Wrong format for InStock number")]
        public int? InStock { get; set; }
        [Required(ErrorMessage = "Amount can not be empty")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Wrong format for Amount number")]
        public decimal? Amount { get; set; }
        public bool? Active { get; set; }

        public virtual ServiceType ServiceType { get; set; }
        public virtual ICollection<ServiceInRoom> ServiceInRoom { get; set; }
    }
}